"""migrate to simplified schema

Revision ID: 9eb9a2ba2fe2
Revises: 001_initial_schema
Create Date: 2026-03-26 04:21:43.580990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9eb9a2ba2fe2'
down_revision: Union[str, Sequence[str], None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('session_uuid', sa.String(length=256), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('measurements', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_profiles_session_uuid'), 'body_profiles', ['session_uuid'], unique=False)
    op.create_table('render_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('job_uuid', sa.String(length=36), nullable=False),
    sa.Column('brand_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('result_url', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_render_jobs_job_uuid'), 'render_jobs', ['job_uuid'], unique=False)
    op.drop_index(op.f('ix_analytics_events_brand_id'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_event_type'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_occurred_at'), table_name='analytics_events')
    op.drop_index(op.f('ix_analytics_events_session_token'), table_name='analytics_events')
    op.drop_table('analytics_events')
    op.drop_table('size_chart_entries')
    op.drop_index(op.f('ix_body_scans_created_at'), table_name='body_scans')
    op.drop_index(op.f('ix_body_scans_session_token'), table_name='body_scans')
    op.drop_table('body_scans')
    op.drop_table('size_charts')
    op.drop_index(op.f('ix_tryon_jobs_brand_status'), table_name='tryon_jobs')
    op.drop_index(op.f('ix_tryon_jobs_queued_at'), table_name='tryon_jobs')
    op.drop_table('tryon_jobs')
    op.drop_table('brand_users')
    op.add_column('brands', sa.Column('api_key', sa.String(length=128), nullable=False))
    op.alter_column('brands', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('brands', 'plan_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'trial'::character varying"))
    op.drop_constraint(op.f('uq_brands_api_key_hash'), 'brands', type_='unique')
    op.drop_constraint(op.f('uq_brands_slug'), 'brands', type_='unique')
    op.create_unique_constraint(None, 'brands', ['api_key'])
    op.drop_column('brands', 'updated_at')
    op.drop_column('brands', 'slug')
    op.drop_column('brands', 'webhook_url')
    op.drop_column('brands', 'api_key_hash')
    op.drop_column('brands', 'created_at')
    op.drop_column('brands', 'stripe_customer_id')
    op.drop_column('brands', 'is_active')
    op.add_column('garments', sa.Column('type', sa.String(length=60), nullable=False))
    op.add_column('garments', sa.Column('sizes', sa.JSON(), nullable=True))
    op.add_column('garments', sa.Column('material_code', sa.String(length=50), nullable=False))
    op.add_column('garments', sa.Column('stretch_coefficient', sa.Float(), nullable=False))
    op.alter_column('garments', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.alter_column('garments', 'brand_id',
               existing_type=sa.UUID(),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.drop_index(op.f('ix_garments_brand_category'), table_name='garments')
    op.drop_column('garments', 'mask_url')
    op.drop_column('garments', 'sku')
    op.drop_column('garments', 'category')
    op.drop_column('garments', 'created_at')
    op.drop_column('garments', 'measurements')
    op.drop_column('garments', 'is_active')
    op.drop_column('garments', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('garments', sa.Column('image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.add_column('garments', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('garments', sa.Column('measurements', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('garments', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('garments', sa.Column('category', sa.VARCHAR(length=60), server_default=sa.text("'upper_body'::character varying"), autoincrement=False, nullable=True))
    op.add_column('garments', sa.Column('sku', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('garments', sa.Column('mask_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_garments_brand_category'), 'garments', ['brand_id', 'category'], unique=False)
    op.alter_column('garments', 'brand_id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.alter_column('garments', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('garments', 'stretch_coefficient')
    op.drop_column('garments', 'material_code')
    op.drop_column('garments', 'sizes')
    op.drop_column('garments', 'type')
    op.add_column('brands', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('stripe_customer_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('api_key_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.add_column('brands', sa.Column('webhook_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.add_column('brands', sa.Column('slug', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('brands', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'brands', type_='unique')
    op.create_unique_constraint(op.f('uq_brands_slug'), 'brands', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_brands_api_key_hash'), 'brands', ['api_key_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('brands', 'plan_tier',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'trial'::character varying"))
    op.alter_column('brands', 'id',
               existing_type=sa.String(length=36),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('brands', 'api_key')
    op.create_table('brand_users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), server_default=sa.text("'admin'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('brand_users_brand_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('brand_users_pkey')),
    sa.UniqueConstraint('brand_id', 'email', name=op.f('uq_brand_user_email'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('tryon_jobs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('garment_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('body_scan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=30), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=True),
    sa.Column('queue_name', sa.VARCHAR(length=60), server_default=sa.text("'aikart_tryon'::character varying"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('5'), autoincrement=False, nullable=True),
    sa.Column('person_image_key', sa.VARCHAR(length=512), autoincrement=False, nullable=True),
    sa.Column('result_image_url', sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('attempt', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('max_retries', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=True),
    sa.Column('progress_pct', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('queued_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('queue_wait_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('inference_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['body_scan_id'], ['body_scans.id'], name=op.f('tryon_jobs_body_scan_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('tryon_jobs_brand_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['garment_id'], ['garments.id'], name=op.f('tryon_jobs_garment_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('tryon_jobs_pkey'))
    )
    op.create_index(op.f('ix_tryon_jobs_queued_at'), 'tryon_jobs', ['queued_at'], unique=False)
    op.create_index(op.f('ix_tryon_jobs_brand_status'), 'tryon_jobs', ['brand_id', 'status'], unique=False)
    op.create_table('size_charts',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('garment_category', sa.VARCHAR(length=60), server_default=sa.text("'upper_body'::character varying"), autoincrement=False, nullable=True),
    sa.Column('region', sa.VARCHAR(length=20), server_default=sa.text("'US'::character varying"), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('size_charts_brand_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('size_charts_pkey')),
    sa.UniqueConstraint('brand_id', 'garment_category', 'region', name=op.f('uq_size_chart'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('body_scans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('brand_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('session_token', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('height_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('weight_kg', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('age_group', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('chest_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waist_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hip_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shoulder_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('inseam_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sleeve_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('neck_cm', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('scan_method', sa.VARCHAR(length=30), server_default=sa.text("'sam3d'::character varying"), autoincrement=False, nullable=True),
    sa.Column('confidence_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('input_quality', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('raw_landmarks', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('scan_duration_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('body_scans_brand_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('body_scans_pkey'))
    )
    op.create_index(op.f('ix_body_scans_session_token'), 'body_scans', ['session_token'], unique=False)
    op.create_index(op.f('ix_body_scans_created_at'), 'body_scans', ['created_at'], unique=False)
    op.create_table('size_chart_entries',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chart_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('size_label', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('chest_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('chest_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waist_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('waist_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hip_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('hip_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shoulder_min', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('shoulder_max', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sort_order', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['chart_id'], ['size_charts.id'], name=op.f('size_chart_entries_chart_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('size_chart_entries_pkey')),
    sa.UniqueConstraint('chart_id', 'size_label', name=op.f('uq_size_chart_entry'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('analytics_events',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('brand_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=60), autoincrement=False, nullable=False),
    sa.Column('session_token', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('garment_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    sa.Column('size_recommended', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.Column('confidence', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('latency_ms', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('extra', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('occurred_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analytics_events_pkey'))
    )
    op.create_index(op.f('ix_analytics_events_session_token'), 'analytics_events', ['session_token'], unique=False)
    op.create_index(op.f('ix_analytics_events_occurred_at'), 'analytics_events', ['occurred_at'], unique=False)
    op.create_index(op.f('ix_analytics_events_event_type'), 'analytics_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_analytics_events_brand_id'), 'analytics_events', ['brand_id'], unique=False)
    op.drop_index(op.f('ix_render_jobs_job_uuid'), table_name='render_jobs')
    op.drop_table('render_jobs')
    op.drop_index(op.f('ix_body_profiles_session_uuid'), table_name='body_profiles')
    op.drop_table('body_profiles')
    # ### end Alembic commands ###
